version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: 
    - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: 
          - zip 

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

# --------------------------------------------------
# Homebrew Cask
# --------------------------------------------------
homebrew_casks:
  - name: "{{ .ProjectName }}"
    description: "URL encoder / decoder CLI tool"
    homepage: "https://github.com/dev-shimada/{{ .ProjectName }}"

    repository:
      owner: dev-shimada
      name: homebrew-{{ .ProjectName }}
      branch: "{{ .ProjectName }}"
      token: "{{ .Env.PRIVATE_GITHUB_TOKEN }}"
      
      pull_request:
        enabled: true
        draft: false
        base:
          branch: main

    binaries: 
      - "{{ .ProjectName }}"
