version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

# --------------------------------------------------
# Homebrew Cask
# --------------------------------------------------
casks:
  - name: urlencode
    description: "URL encoder / decoder CLI tool"
    homepage: "https://github.com/dev-shimada/urlencode"

    repository:
      owner: dev-shimada
      name: homebrew-urlencode
      branch: main
      token: "{{ .Env.PRIVATE_GITHUB_TOKEN }}"

      pull_request:
        enabled: true
        draft: false

    binary: urlencode

    # 補完ファイル生成
    postflight: |
      system_command "#{bin}/urlencode", args: ["completion", "bash"], stdout: "#{bash_completion}/urlencode"
      system_command "#{bin}/urlencode", args: ["completion", "zsh"],  stdout: "#{zsh_completion}/_urlencode"
      system_command "#{bin}/urlencode", args: ["completion", "fish"], stdout: "#{fish_completion}/urlencode.fish"

    uninstall_postflight: |
      rm_f "#{bash_completion}/urlencode"
      rm_f "#{zsh_completion}/_urlencode"
      rm_f "#{fish_completion}/urlencode.fish"
