name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest

    - name: Go Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...

    # - name: Run Unit tests
    #   run: |
    #     go test -race -covermode atomic -coverprofile=covprofile ./...

    # - name: Install goveralls
    #   run: go install github.com/mattn/goveralls@latest

    # - name: Send coverage
    #   env:
    #     COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: goveralls -coverprofile=covprofile -service=github
